version: '3.8'

services:
  db:
    image: postgres:14
    container_name: postgres_alembic
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: alembic_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
